language: c
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libssl-dev zlib1g-dev libtre-dev libc-ares-dev autoconf automake libtool bash
script: sh ./extras/ci-build.sh
notifications:
  irc:
    channels:
      - "irc.weresource.org#ircd"
    on_success: change
    on_failure: always
